services:
  
  nginx:
    container_name: nginx
    image: nginx:latest

    ports:
      - "8080:80"
    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php-fpm
      
  php-fpm:
    container_name: php-fpm
    build: 
      dockerfile: ./php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./src:/src
    
  
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Sandbox
    ports:
      - "8090:3306"