services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      dockerfile: ./php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ../src:/var/www/


  mysql:
    image: mysql:latest
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Sandbox
    ports:
      - "8090:3306"

  ftp:
    container_name: ftp-server
    image: garethflowers/ftp-server
    environment:
      - FTP_USER=simplyfuze
      - FTP_PASS=simplyfuze
    restart: always
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'   # passive mode
    volumes:
      - ../shared:/home/simplyfuze/shared
